"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
$directory\
$package\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\

$fill \

$docker_context\
$lua\
$nodejs\
$python\
$rust\
$line_break\
$character\
"""

[directory]
read_only = " "

[docker_context]
symbol = " "

[fill]
symbol = "·"

[git_branch]
symbol = " "

[hostname]
ssh_symbol = ""

[lua]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "
not_capable_style = "bold yellow"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
